### PR TITLE
feat: update releases

### PR DESCRIPTION
**Pull request by smira**
Linux: 6.6.18
ZFS: 2.2.3 (should fix the Linux 6.6 build failure)
iPXE: bump to next main

### CODE REVIEW

**Review by frezbo — APPROVED** [review]
seems there's also an update for rpi firmware and xz

**Comment by smira** [comment]
> seems there's also an update for rpi firmware and xz

yes, that's true. I don't want to put too much here for now - I want to see if ZFS got fixed first.

**Comment by smira** [comment]
> > seems there's also an update for rpi firmware and xz
> 
> yes, that's true. I don't want to put too much here for now - I want to see if ZFS got fixed first.

and it did build :dancers:

**Pull request merged**
