### PR TITLE
feat: enable modules for mlx infiniband

### PR DESCRIPTION
**Pull request by yoctozepto**
mlx4 and mlx5 core and ethernet modules are enabled. Infiniband and IPoIB are also enabled.
And this patch enables the remaining bits to get most Infiniband hardware working out of the box.

Requires inclusion of the new modules in the list for initramfs to support cases like booting from or otherwise early use of the Infiniband network.

### CODE REVIEW

**Review by smira — APPROVED** [review]

**Comment by smira** [comment]
module diff:

```diff
75a76,80
> ./lib/modules/6.1.67-talos/kernel/drivers/infiniband/hw
> ./lib/modules/6.1.67-talos/kernel/drivers/infiniband/hw/mlx4
> ./lib/modules/6.1.67-talos/kernel/drivers/infiniband/hw/mlx4/mlx4_ib.ko
> ./lib/modules/6.1.67-talos/kernel/drivers/infiniband/hw/mlx5
> ./lib/modules/6.1.67-talos/kernel/drivers/infiniband/hw/mlx5/mlx5_ib.ko
301c306
< 109 directories, 190 files
---
> 112 directories, 192 files
```

new modules size:

```
            │   │   ├── [4.0K]  infiniband
            │   │   │   ├── [4.0K]  hw
            │   │   │   │   ├── [4.0K]  mlx4
            │   │   │   │   │   └── [425K]  mlx4_ib.ko
            │   │   │   │   └── [4.0K]  mlx5
            │   │   │   │       └── [627K]  mlx5_ib.ko
```

**Review by frezbo — APPROVED** [review]

**Comment by smira** [comment]
looks like these modules need to be loaded explicitly. I wonder if they should go to a system extension?

**Comment by yoctozepto** [comment]
Nope, they get loaded automatically by core when it senses a port configured for Infiniband.

**Comment by yoctozepto** [comment]
(continuing on the previous comment)

Analogously, when core senses an Ethernet port, it loads the _en module (and this is now working out of the box).

**Comment by smira** [comment]
```diff
263a264,270
> ./lib/modules/6.1.67-talos/kernel/drivers/vfio
> ./lib/modules/6.1.67-talos/kernel/drivers/vfio/pci
> ./lib/modules/6.1.67-talos/kernel/drivers/vfio/pci/vfio-pci-core.ko
> ./lib/modules/6.1.67-talos/kernel/drivers/vfio/pci/vfio-pci.ko
> ./lib/modules/6.1.67-talos/kernel/drivers/vfio/vfio_iommu_type1.ko
> ./lib/modules/6.1.67-talos/kernel/drivers/vfio/vfio.ko
> ./lib/modules/6.1.67-talos/kernel/drivers/vfio/vfio_virqfd.ko
301c308
< 109 directories, 190 files
---
> 111 directories, 195 files
```

Size:

```
            │   │   ├── [4.0K]  vfio
            │   │   │   ├── [4.0K]  pci
            │   │   │   │   ├── [155K]  vfio-pci-core.ko
            │   │   │   │   └── [ 23K]  vfio-pci.ko
            │   │   │   ├── [ 83K]  vfio_iommu_type1.ko
            │   │   │   ├── [ 90K]  vfio.ko
            │   │   │   └── [ 15K]  vfio_virqfd.ko
```

**Pull request merged**
