### PR TITLE
feat: enable nct6683 sensors as module

### PR DESCRIPTION
**Pull request by JJGadgets**
The Lenovo Tiny M720q, as well as other Lenovo Tiny ThinkCentres (https://forums.servethehome.com/index.php?threads/lenovo-thinkcentre-thinkstation-tiny-project-tinyminimicro-reference-thread.34925/), uses this kernel module to expose hardware sensor metrics such as voltages, fan speed, and temperatures (CPU and others).

### CODE REVIEW

**Comment by JJGadgets** [comment]
Do I need to re-commit using my actual PGP key to sign the commit? I used GitHub.com to edit the file and PR so it's currently signed with their key.

**Comment by JJGadgets** [comment]
Re-committed and force-pushed anyway for the DCO.

**Comment by frezbo** [comment]
thanks :+1: , will clean up and merged

**Comment by smira** [comment]
let's merge after #844

**Review by frezbo — APPROVED** [review]

**Pull request merged**
