### PR TITLE
chore: bump deps

### PR DESCRIPTION
**Pull request by DmitriyMV**
Bump deps:
- tools
- linux firmware
- ipxe
- linux kernel

Signed-off-by: Dmitriy Matrenichev <dmitry.matrenichev@siderolabs.com>

### CODE REVIEW

**Comment by frezbo** [comment]
#574 missing?

**Comment by smira** [comment]
let's not bump containerd for now, let's stay on 1.16.x

**Comment by frezbo** [comment]
let's fix the renovate config for util-linux too https://github.com/siderolabs/tools/pull/281

**Comment by DmitriyMV** [comment]
> let's not bump containerd for now, let's stay on 1.16.x

Done.

> let's fix the renovate config for util-linux too https://github.com/siderolabs/tools/pull/281

Done, I think.

**Review by frezbo — APPROVED** [review]

**Review by smira — APPROVED** [review]

**Pull request merged**
