### PR TITLE
fix: re-introduce BCM arch for arm64 kernel

### PR DESCRIPTION
**Pull request by xvzf**
fixes https://github.com/siderolabs/pkgs/issues/642

Signed-off-by: Matthias Riegler <me@xvzf.tech>

### CODE REVIEW

**Comment by smira** [comment]
there seem to be many more things to fix, I'm going slowly over it

**Comment by xvzf** [comment]
Alright, feel free to close it! At least for the CM4 I tested, this fixes it

**Comment by smira** [comment]
there are some additional power/poe settings... and other SoCs as well

**Comment by smira** [comment]
#653 has more fixes, thanks

**Pull request closed without merging**
