### PR TITLE
feat: split more device drivers into modules

### PR DESCRIPTION
**Pull request by smira**
I went over all options which are `=y` in Talos, but `=m` in e.g. Ubuntu, and cross-referenced with lkddb to make sure each option is a driver loadable by PCI or USB IDs.

The goal is to have smaller kernel, less stuff loaded by default, and shorter boot times.

The final diff on modules:

```
22a23,64
> ./lib/modules/6.1.65-talos/kernel/drivers/ata
> ./lib/modules/6.1.65-talos/kernel/drivers/ata/ahci.ko
> ./lib/modules/6.1.65-talos/kernel/drivers/ata/libahci.ko
> ./lib/modules/6.1.65-talos/kernel/drivers/ata/pata_amd.ko
> ./lib/modules/6.1.65-talos/kernel/drivers/ata/pata_marvell.ko
> ./lib/modules/6.1.65-talos/kernel/drivers/ata/pata_oldpiix.ko
> ./lib/modules/6.1.65-talos/kernel/drivers/ata/pata_sch.ko
> ./lib/modules/6.1.65-talos/kernel/drivers/gpu
> ./lib/modules/6.1.65-talos/kernel/drivers/gpu/drm
> ./lib/modules/6.1.65-talos/kernel/drivers/gpu/drm/amd
> ./lib/modules/6.1.65-talos/kernel/drivers/gpu/drm/amd/amdgpu
> ./lib/modules/6.1.65-talos/kernel/drivers/gpu/drm/amd/amdgpu/amdgpu.ko
> ./lib/modules/6.1.65-talos/kernel/drivers/gpu/drm/display
> ./lib/modules/6.1.65-talos/kernel/drivers/gpu/drm/display/drm_display_helper.ko
> ./lib/modules/6.1.65-talos/kernel/drivers/gpu/drm/drm_buddy.ko
> ./lib/modules/6.1.65-talos/kernel/drivers/gpu/drm/drm_ttm_helper.ko
> ./lib/modules/6.1.65-talos/kernel/drivers/gpu/drm/i915
> ./lib/modules/6.1.65-talos/kernel/drivers/gpu/drm/i915/i915.ko
> ./lib/modules/6.1.65-talos/kernel/drivers/gpu/drm/scheduler
> ./lib/modules/6.1.65-talos/kernel/drivers/gpu/drm/scheduler/gpu-sched.ko
> ./lib/modules/6.1.65-talos/kernel/drivers/gpu/drm/ttm
> ./lib/modules/6.1.65-talos/kernel/drivers/gpu/drm/ttm/ttm.ko
> ./lib/modules/6.1.65-talos/kernel/drivers/hid
> ./lib/modules/6.1.65-talos/kernel/drivers/hid/hid-a4tech.ko
> ./lib/modules/6.1.65-talos/kernel/drivers/hid/hid-apple.ko
> ./lib/modules/6.1.65-talos/kernel/drivers/hid/hid-belkin.ko
> ./lib/modules/6.1.65-talos/kernel/drivers/hid/hid-cherry.ko
> ./lib/modules/6.1.65-talos/kernel/drivers/hid/hid-chicony.ko
> ./lib/modules/6.1.65-talos/kernel/drivers/hid/hid-cypress.ko
> ./lib/modules/6.1.65-talos/kernel/drivers/hid/hid-ezkey.ko
> ./lib/modules/6.1.65-talos/kernel/drivers/hid/hid-gyration.ko
> ./lib/modules/6.1.65-talos/kernel/drivers/hid/hid-ite.ko
> ./lib/modules/6.1.65-talos/kernel/drivers/hid/hid-kensington.ko
> ./lib/modules/6.1.65-talos/kernel/drivers/hid/hid-lg-g15.ko
> ./lib/modules/6.1.65-talos/kernel/drivers/hid/hid-logitech.ko
> ./lib/modules/6.1.65-talos/kernel/drivers/hid/hid-microsoft.ko
> ./lib/modules/6.1.65-talos/kernel/drivers/hid/hid-monterey.ko
> ./lib/modules/6.1.65-talos/kernel/drivers/hid/hid-petalynx.ko
> ./lib/modules/6.1.65-talos/kernel/drivers/hid/hid-pl.ko
> ./lib/modules/6.1.65-talos/kernel/drivers/hid/hid-samsung.ko
> ./lib/modules/6.1.65-talos/kernel/drivers/hid/hid-sunplus.ko
> ./lib/modules/6.1.65-talos/kernel/drivers/hid/hid-topseed.ko
28a71,74
> ./lib/modules/6.1.65-talos/kernel/drivers/i2c
> ./lib/modules/6.1.65-talos/kernel/drivers/i2c/busses
> ./lib/modules/6.1.65-talos/kernel/drivers/i2c/busses/i2c-i801.ko
> ./lib/modules/6.1.65-talos/kernel/drivers/i2c/i2c-smbus.ko
41a88,101
> ./lib/modules/6.1.65-talos/kernel/drivers/message
> ./lib/modules/6.1.65-talos/kernel/drivers/message/fusion
> ./lib/modules/6.1.65-talos/kernel/drivers/message/fusion/mptbase.ko
> ./lib/modules/6.1.65-talos/kernel/drivers/message/fusion/mptsas.ko
> ./lib/modules/6.1.65-talos/kernel/drivers/message/fusion/mptscsih.ko
> ./lib/modules/6.1.65-talos/kernel/drivers/misc
> ./lib/modules/6.1.65-talos/kernel/drivers/misc/hpilo.ko
> ./lib/modules/6.1.65-talos/kernel/drivers/mmc
> ./lib/modules/6.1.65-talos/kernel/drivers/mmc/host
> ./lib/modules/6.1.65-talos/kernel/drivers/mmc/host/sdhci-acpi.ko
> ./lib/modules/6.1.65-talos/kernel/drivers/mmc/host/sdhci_f_sdh30.ko
> ./lib/modules/6.1.65-talos/kernel/drivers/mmc/host/sdhci-pci.ko
> ./lib/modules/6.1.65-talos/kernel/drivers/mmc/host/sdhci-pltfm.ko
> ./lib/modules/6.1.65-talos/kernel/drivers/mmc/host/sdhci-xenon-driver.ko
55a116,119
> ./lib/modules/6.1.65-talos/kernel/drivers/net/ethernet/broadcom/tg3.ko
> ./lib/modules/6.1.65-talos/kernel/drivers/net/ethernet/cavium
> ./lib/modules/6.1.65-talos/kernel/drivers/net/ethernet/cavium/common
> ./lib/modules/6.1.65-talos/kernel/drivers/net/ethernet/cavium/common/cavium_ptp.ko
118a183,184
> ./lib/modules/6.1.65-talos/kernel/drivers/net/ethernet/qlogic/netxen
> ./lib/modules/6.1.65-talos/kernel/drivers/net/ethernet/qlogic/netxen/netxen_nic.ko
131a198
> ./lib/modules/6.1.65-talos/kernel/drivers/net/mii.ko
156a224
> ./lib/modules/6.1.65-talos/kernel/drivers/net/usb/r8152.ko
167a236,238
> ./lib/modules/6.1.65-talos/kernel/drivers/nvme
> ./lib/modules/6.1.65-talos/kernel/drivers/nvme/host
> ./lib/modules/6.1.65-talos/kernel/drivers/nvme/host/nvme.ko
171a243,244
> ./lib/modules/6.1.65-talos/kernel/drivers/scsi/isci
> ./lib/modules/6.1.65-talos/kernel/drivers/scsi/isci/isci.ko
184a258,260
> ./lib/modules/6.1.65-talos/kernel/drivers/usb/serial/ch341.ko
> ./lib/modules/6.1.65-talos/kernel/drivers/usb/serial/cp210x.ko
> ./lib/modules/6.1.65-talos/kernel/drivers/usb/serial/ftdi_sio.ko
185a262
> ./lib/modules/6.1.65-talos/kernel/drivers/usb/serial/pl2303.ko
224c301
< 86 directories, 136 files
---
> 109 directories, 190 files
```

### CODE REVIEW

**Comment by smira** [comment]
New (full) module tree:

<details>

```
4.0K]  .
└── [4.0K]  modules
    └── [4.0K]  6.1.65-talos
        ├── [4.0K]  kernel
        │   ├── [4.0K]  crypto
        │   │   ├── [4.0K]  async_tx
        │   │   │   ├── [9.9K]  async_memcpy.ko
        │   │   │   ├── [ 19K]  async_pq.ko
        │   │   │   ├── [9.9K]  async_raid6_recov.ko
        │   │   │   ├── [ 13K]  async_tx.ko
        │   │   │   └── [ 16K]  async_xor.ko
        │   │   ├── [ 24K]  blake2b_generic.ko
        │   │   ├── [ 28K]  xor.ko
        │   │   ├── [9.8K]  xxhash_generic.ko
        │   │   └── [ 16K]  zstd.ko
        │   ├── [4.0K]  drivers
        │   │   ├── [4.0K]  ata
        │   │   │   ├── [ 96K]  ahci.ko
        │   │   │   ├── [ 94K]  libahci.ko
        │   │   │   ├── [ 34K]  pata_amd.ko
        │   │   │   ├── [ 16K]  pata_marvell.ko
        │   │   │   ├── [ 17K]  pata_oldpiix.ko
        │   │   │   └── [ 14K]  pata_sch.ko
        │   │   ├── [4.0K]  gpu
        │   │   │   └── [4.0K]  drm
        │   │   │       ├── [4.0K]  amd
        │   │   │       │   └── [4.0K]  amdgpu
        │   │   │       │       └── [ 16M]  amdgpu.ko
        │   │   │       ├── [4.0K]  display
        │   │   │       │   └── [320K]  drm_display_helper.ko
        │   │   │       ├── [ 27K]  drm_buddy.ko
        │   │   │       ├── [ 15K]  drm_ttm_helper.ko
        │   │   │       ├── [4.0K]  i915
        │   │   │       │   └── [6.3M]  i915.ko
        │   │   │       ├── [4.0K]  scheduler
        │   │   │       │   └── [ 97K]  gpu-sched.ko
        │   │   │       └── [4.0K]  ttm
        │   │   │           └── [180K]  ttm.ko
        │   │   ├── [4.0K]  hid
        │   │   │   ├── [ 12K]  hid-a4tech.ko
        │   │   │   ├── [ 39K]  hid-apple.ko
        │   │   │   ├── [ 11K]  hid-belkin.ko
        │   │   │   ├── [ 11K]  hid-cherry.ko
        │   │   │   ├── [ 18K]  hid-chicony.ko
        │   │   │   ├── [ 12K]  hid-cypress.ko
        │   │   │   ├── [ 10K]  hid-ezkey.ko
        │   │   │   ├── [ 14K]  hid-gyration.ko
        │   │   │   ├── [ 13K]  hid-ite.ko
        │   │   │   ├── [9.3K]  hid-kensington.ko
        │   │   │   ├── [ 32K]  hid-lg-g15.ko
        │   │   │   ├── [ 88K]  hid-logitech.ko
        │   │   │   ├── [ 23K]  hid-microsoft.ko
        │   │   │   ├── [ 11K]  hid-monterey.ko
        │   │   │   ├── [ 13K]  hid-petalynx.ko
        │   │   │   ├── [ 12K]  hid-pl.ko
        │   │   │   ├── [ 16K]  hid-samsung.ko
        │   │   │   ├── [ 10K]  hid-sunplus.ko
        │   │   │   └── [ 17K]  hid-topseed.ko
        │   │   ├── [4.0K]  hwmon
        │   │   │   ├── [ 23K]  fam15h_power.ko
        │   │   │   ├── [ 12K]  i5500_temp.ko
        │   │   │   ├── [ 23K]  i5k_amb.ko
        │   │   │   ├── [ 26K]  k10temp.ko
        │   │   │   └── [ 14K]  k8temp.ko
        │   │   ├── [4.0K]  i2c
        │   │   │   ├── [4.0K]  busses
        │   │   │   │   └── [ 55K]  i2c-i801.ko
        │   │   │   └── [ 19K]  i2c-smbus.ko
        │   │   ├── [4.0K]  infiniband
        │   │   │   └── [4.0K]  sw
        │   │   │       └── [4.0K]  rxe
        │   │   │           └── [234K]  rdma_rxe.ko
        │   │   ├── [4.0K]  md
        │   │   │   ├── [ 38K]  dm-bio-prison.ko
        │   │   │   ├── [ 75K]  dm-multipath.ko
        │   │   │   ├── [ 79K]  dm-raid.ko
        │   │   │   ├── [ 17K]  dm-round-robin.ko
        │   │   │   ├── [196K]  dm-thin-pool.ko
        │   │   │   ├── [4.0K]  persistent-data
        │   │   │   │   └── [225K]  dm-persistent-data.ko
        │   │   │   └── [321K]  raid456.ko
        │   │   ├── [4.0K]  message
        │   │   │   └── [4.0K]  fusion
        │   │   │       ├── [169K]  mptbase.ko
        │   │   │       ├── [131K]  mptsas.ko
        │   │   │       └── [ 77K]  mptscsih.ko
        │   │   ├── [4.0K]  misc
        │   │   │   └── [ 32K]  hpilo.ko
        │   │   ├── [4.0K]  mmc
        │   │   │   └── [4.0K]  host
        │   │   │       ├── [ 40K]  sdhci-acpi.ko
        │   │   │       ├── [ 16K]  sdhci_f_sdh30.ko
        │   │   │       ├── [154K]  sdhci-pci.ko
        │   │   │       ├── [ 20K]  sdhci-pltfm.ko
        │   │   │       └── [ 48K]  sdhci-xenon-driver.ko
        │   │   ├── [4.0K]  net
        │   │   │   ├── [4.0K]  ethernet
        │   │   │   │   ├── [4.0K]  aquantia
        │   │   │   │   │   └── [4.0K]  atlantic
        │   │   │   │   │       └── [516K]  atlantic.ko
        │   │   │   │   ├── [4.0K]  atheros
        │   │   │   │   │   └── [4.0K]  alx
        │   │   │   │   │       └── [104K]  alx.ko
        │   │   │   │   ├── [4.0K]  broadcom
        │   │   │   │   │   ├── [188K]  bnx2.ko
        │   │   │   │   │   ├── [4.0K]  bnx2x
        │   │   │   │   │   │   └── [1.6M]  bnx2x.ko
        │   │   │   │   │   ├── [4.0K]  bnxt
        │   │   │   │   │   │   └── [721K]  bnxt_en.ko
        │   │   │   │   │   └── [384K]  tg3.ko
        │   │   │   │   ├── [4.0K]  cavium
        │   │   │   │   │   └── [4.0K]  common
        │   │   │   │   │       └── [ 17K]  cavium_ptp.ko
        │   │   │   │   ├── [4.0K]  chelsio
        │   │   │   │   │   ├── [4.0K]  cxgb
        │   │   │   │   │   │   └── [173K]  cxgb.ko
        │   │   │   │   │   ├── [4.0K]  cxgb3
        │   │   │   │   │   │   └── [398K]  cxgb3.ko
        │   │   │   │   │   ├── [4.0K]  cxgb4
        │   │   │   │   │   │   └── [1.4M]  cxgb4.ko
        │   │   │   │   │   ├── [4.0K]  cxgb4vf
        │   │   │   │   │   │   └── [208K]  cxgb4vf.ko
        │   │   │   │   │   └── [4.0K]  inline_crypto
        │   │   │   │   │       └── [4.0K]  ch_ipsec
        │   │   │   │   │           └── [ 44K]  ch_ipsec.ko
        │   │   │   │   ├── [4.0K]  cisco
        │   │   │   │   │   └── [4.0K]  enic
        │   │   │   │   │       └── [241K]  enic.ko
        │   │   │   │   ├── [4.0K]  emulex
        │   │   │   │   │   └── [4.0K]  benet
        │   │   │   │   │       └── [351K]  be2net.ko
        │   │   │   │   ├── [4.0K]  google
        │   │   │   │   │   └── [4.0K]  gve
        │   │   │   │   │       └── [175K]  gve.ko
        │   │   │   │   ├── [4.0K]  intel
        │   │   │   │   │   ├── [4.0K]  e1000
        │   │   │   │   │   │   └── [259K]  e1000.ko
        │   │   │   │   │   ├── [4.0K]  e1000e
        │   │   │   │   │   │   └── [528K]  e1000e.ko
        │   │   │   │   │   ├── [106K]  e100.ko
        │   │   │   │   │   ├── [4.0K]  i40e
        │   │   │   │   │   │   └── [961K]  i40e.ko
        │   │   │   │   │   ├── [4.0K]  iavf
        │   │   │   │   │   │   └── [360K]  iavf.ko
        │   │   │   │   │   ├── [4.0K]  ice
        │   │   │   │   │   │   └── [1.6M]  ice.ko
        │   │   │   │   │   ├── [4.0K]  igb
        │   │   │   │   │   │   └── [497K]  igb.ko
        │   │   │   │   │   ├── [4.0K]  igbvf
        │   │   │   │   │   │   └── [109K]  igbvf.ko
        │   │   │   │   │   ├── [4.0K]  igc
        │   │   │   │   │   │   └── [290K]  igc.ko
        │   │   │   │   │   ├── [4.0K]  ixgb
        │   │   │   │   │   │   └── [111K]  ixgb.ko
        │   │   │   │   │   ├── [4.0K]  ixgbe
        │   │   │   │   │   │   └── [732K]  ixgbe.ko
        │   │   │   │   │   └── [4.0K]  ixgbevf
        │   │   │   │   │       └── [178K]  ixgbevf.ko
        │   │   │   │   ├── [4.0K]  marvell
        │   │   │   │   │   └── [158K]  sky2.ko
        │   │   │   │   ├── [4.0K]  mellanox
        │   │   │   │   │   ├── [4.0K]  mlx4
        │   │   │   │   │   │   ├── [825K]  mlx4_core.ko
        │   │   │   │   │   │   └── [333K]  mlx4_en.ko
        │   │   │   │   │   ├── [4.0K]  mlx5
        │   │   │   │   │   │   └── [4.0K]  core
        │   │   │   │   │   │       └── [3.4M]  mlx5_core.ko
        │   │   │   │   │   ├── [4.0K]  mlxfw
        │   │   │   │   │   │   └── [ 47K]  mlxfw.ko
        │   │   │   │   │   └── [4.0K]  mlxsw
        │   │   │   │   │       ├── [460K]  mlxsw_core.ko
        │   │   │   │   │       ├── [ 27K]  mlxsw_i2c.ko
        │   │   │   │   │       ├── [ 41K]  mlxsw_minimal.ko
        │   │   │   │   │       ├── [ 77K]  mlxsw_pci.ko
        │   │   │   │   │       └── [1.5M]  mlxsw_spectrum.ko
        │   │   │   │   ├── [4.0K]  qlogic
        │   │   │   │   │   ├── [4.0K]  netxen
        │   │   │   │   │   │   └── [273K]  netxen_nic.ko
        │   │   │   │   │   ├── [4.0K]  qed
        │   │   │   │   │   │   └── [1.3M]  qed.ko
        │   │   │   │   │   ├── [4.0K]  qede
        │   │   │   │   │   │   └── [359K]  qede.ko
        │   │   │   │   │   └── [4.0K]  qlcnic
        │   │   │   │   │       └── [806K]  qlcnic.ko
        │   │   │   │   ├── [4.0K]  realtek
        │   │   │   │   │   ├── [ 71K]  8139too.ko
        │   │   │   │   │   └── [206K]  r8169.ko
        │   │   │   │   └── [4.0K]  sfc
        │   │   │   │       └── [4.0K]  siena
        │   │   │   │           └── [506K]  sfc-siena.ko
        │   │   │   ├── [ 19K]  mdio.ko
        │   │   │   ├── [ 22K]  mii.ko
        │   │   │   ├── [4.0K]  phy
        │   │   │   │   ├── [ 12K]  ax88796b.ko
        │   │   │   │   └── [ 21K]  smsc.ko
        │   │   │   ├── [ 51K]  thunderbolt-net.ko
        │   │   │   ├── [4.0K]  usb
        │   │   │   │   ├── [ 54K]  aqc111.ko
        │   │   │   │   ├── [103K]  asix.ko
        │   │   │   │   ├── [ 59K]  ax88179_178a.ko
        │   │   │   │   ├── [ 16K]  cdc_eem.ko
        │   │   │   │   ├── [ 34K]  cdc_ether.ko
        │   │   │   │   ├── [ 30K]  cdc_mbim.ko
        │   │   │   │   ├── [ 67K]  cdc_ncm.ko
        │   │   │   │   ├── [ 23K]  cdc-phonet.ko
        │   │   │   │   ├── [ 15K]  cdc_subset.ko
        │   │   │   │   ├── [ 22K]  cx82310_eth.ko
        │   │   │   │   ├── [ 33K]  dm9601.ko
        │   │   │   │   ├── [ 14K]  gl620a.ko
        │   │   │   │   ├── [ 19K]  huawei_cdc_ncm.ko
        │   │   │   │   ├── [ 17K]  int51x1.ko
        │   │   │   │   ├── [ 17K]  kalmia.ko
        │   │   │   │   ├── [ 18K]  lg-vl600.ko
        │   │   │   │   ├── [ 29K]  mcs7830.ko
        │   │   │   │   ├── [ 17K]  net1080.ko
        │   │   │   │   ├── [ 11K]  plusb.ko
        │   │   │   │   ├── [103K]  qmi_wwan.ko
        │   │   │   │   ├── [237K]  r8152.ko
        │   │   │   │   ├── [ 15K]  r8153_ecm.ko
        │   │   │   │   ├── [ 31K]  rndis_host.ko
        │   │   │   │   ├── [ 35K]  sierra_net.ko
        │   │   │   │   ├── [ 80K]  smsc75xx.ko
        │   │   │   │   ├── [ 73K]  smsc95xx.ko
        │   │   │   │   ├── [ 30K]  sr9700.ko
        │   │   │   │   ├── [ 38K]  sr9800.ko
        │   │   │   │   ├── [ 89K]  usbnet.ko
        │   │   │   │   └── [ 17K]  zaurus.ko
        │   │   │   └── [4.0K]  vmxnet3
        │   │   │       └── [127K]  vmxnet3.ko
        │   │   ├── [4.0K]  nvme
        │   │   │   └── [4.0K]  host
        │   │   │       └── [108K]  nvme.ko
        │   │   ├── [4.0K]  scsi
        │   │   │   ├── [4.0K]  aacraid
        │   │   │   │   └── [319K]  aacraid.ko
        │   │   │   ├── [235K]  hpsa.ko
        │   │   │   ├── [4.0K]  isci
        │   │   │   │   └── [313K]  isci.ko
        │   │   │   ├── [4.0K]  megaraid
        │   │   │   │   └── [379K]  megaraid_sas.ko
        │   │   │   ├── [4.0K]  mpt3sas
        │   │   │   │   └── [790K]  mpt3sas.ko
        │   │   │   ├── [4.0K]  smartpqi
        │   │   │   │   └── [264K]  smartpqi.ko
        │   │   │   └── [ 52K]  vmw_pvscsi.ko
        │   │   ├── [4.0K]  thunderbolt
        │   │   │   └── [699K]  thunderbolt.ko
        │   │   ├── [4.0K]  usb
        │   │   │   ├── [4.0K]  class
        │   │   │   │   └── [ 47K]  cdc-wdm.ko
        │   │   │   └── [4.0K]  serial
        │   │   │       ├── [ 31K]  ch341.ko
        │   │   │       ├── [ 56K]  cp210x.ko
        │   │   │       ├── [150K]  ftdi_sio.ko
        │   │   │       ├── [183K]  option.ko
        │   │   │       ├── [ 43K]  pl2303.ko
        │   │   │       └── [ 29K]  usb_wwan.ko
        │   │   └── [4.0K]  virtio
        │   │       ├── [ 46K]  virtio_balloon.ko
        │   │       ├── [ 27K]  virtio_input.ko
        │   │       ├── [ 33K]  virtio_mmio.ko
        │   │       ├── [ 60K]  virtio_pci.ko
        │   │       ├── [ 16K]  virtio_pci_legacy_dev.ko
        │   │       └── [ 31K]  virtio_pci_modern_dev.ko
        │   ├── [4.0K]  fs
        │   │   ├── [ 28K]  binfmt_misc.ko
        │   │   └── [4.0K]  btrfs
        │   │       └── [3.5M]  btrfs.ko
        │   ├── [4.0K]  lib
        │   │   ├── [ 98K]  objagg.ko
        │   │   ├── [ 14K]  parman.ko
        │   │   ├── [4.0K]  raid6
        │   │   │   └── [145K]  raid6_pq.ko
        │   │   └── [4.0K]  zstd
        │   │       └── [460K]  zstd_compress.ko
        │   └── [4.0K]  net
        │       ├── [4.0K]  ipv4
        │       │   └── [ 57K]  ip_gre.ko
        │       └── [4.0K]  openvswitch
        │           └── [9.3K]  vport-gre.ko
        ├── [329K]  modules.alias
        ├── [300K]  modules.alias.bin
        ├── [ 24K]  modules.builtin
        ├── [ 28K]  modules.builtin.alias.bin
        ├── [ 27K]  modules.builtin.bin
        ├── [178K]  modules.builtin.modinfo
        ├── [ 12K]  modules.dep
        ├── [ 20K]  modules.dep.bin
        ├── [  80]  modules.devname
        ├── [6.7K]  modules.order
        ├── [ 193]  modules.softdep
        ├── [ 59K]  modules.symbols
        └── [ 69K]  modules.symbols.bin

105 directories, 188 files
```

</details>

**Review by frezbo — APPROVED** [review]
amd64 only i guess for now?

**Comment by smira** [comment]
> amd64 only i guess for now?

yes... I think we need to do a lot of modules for arm64... like really a lot, splitting up SBC stuff

**Pull request merged**
