### PR TITLE
feat: add nvidia open gpu kernel modules

### PR DESCRIPTION
**Pull request by frezbo**
Add NVIDIA open gpu kernel modules

Ref: https://developer.nvidia.com/blog/nvidia-releases-open-source-gpu-kernel-modules/

Signed-off-by: Noel Georgi <git@frezbo.dev>

### CODE REVIEW

**Comment by frezbo** [comment]
@smira i think we can create a system extension based on this released container image (we might need a kernel version constraint in the extension spec). I'm also not sure how to handle if the same kernel version is re-built as the signing key changes)

**Comment by smira** [comment]
@frezbo I think we can do that easily if we pull exact `PKGS` version matching the release of Talos. So system extension will work exactly with the version of Talos it was built against. 

In other words, this package `nvidia-open-gpu-kernel-module` should match exactly `kernel` tag.

**Comment by smira** [comment]
Or what this means we should rebuild/bump extensions for each Talos release.

**Comment by frezbo** [comment]
> In other words, this package nvidia-open-gpu-kernel-module should match exactly kernel tag.

yeh, i was wondering the same as talos could have a pkgs bump if some other component got update

**Review by smira — APPROVED** [review]

**Pull request merged**
