### PR TITLE
feat: enable NET_IPGRE kernel config

### PR DESCRIPTION
**Pull request by lion7**
allow Talos to use GRE tunnels

### CODE REVIEW

**Comment by smira** [comment]
@lion7 updated your PR with make olddefconfig

**Comment by smira** [comment]
reworked as kernel modules:

```
│   └── [ 78K]  net
│       ├── [ 61K]  ipv4
│       │   └── [ 57K]  ip_gre.ko
│       └── [ 13K]  openvswitch
│           └── [9.3K]  vport-gre.ko
```

To add to Talos initramfs:

```
./kernel/net/ipv4
./kernel/net/ipv4/ip_gre.ko
./kernel/net/openvswitch
./kernel/net/openvswitch/vport-gre.ko
```

**Review by frezbo — APPROVED** [review]

**Comment by lion7** [comment]
Hmm, maybe I missed something but how do I activate such a module?

**Pull request merged**
