### PR TITLE
feat: add AMD K10 sensor support

### PR DESCRIPTION
**Pull request by cvandesande**
Allows the Prometheus node exporter to export AMD CPU sensor data for hardware monitoring

### CODE REVIEW

**Comment by rsmitty** [comment]
hey @cvandesande, thx for the PR. you'll definitely want to do the DCO and the commit body for this to get merged. don't sweat the gpg signature, I can check it out and sign it before merging.

**Comment by cvandesande** [comment]
Down to 1 failing check, I guess it doesn't like my GPG authority...which is me 😁️

**Comment by rsmitty** [comment]
yep, no that's fine. it _has_ to be signed by one of us sidero devs.

**Review by rsmitty — APPROVED** [review]

**Pull request merged**
