### PR TITLE
feat: Enable nvme multipath and auth

### LINKED ISSUE #741: Enable CONFIG_NVME_MULTIPATH
Native nvme multipath is needed for democratic-csi nvmeof https://github.com/democratic-csi/democratic-csi/blob/master/README.md?plain=1#L221

### PR DESCRIPTION
**Pull request by ishioni**
Enable CONFIG_NVME_MULTIPATH and CONFIG_NVME_AUTH

This enables the democratic-csi nvmeof driver to run, and enables (optional) authentication of such connections. Closes #741

### CODE REVIEW

**Comment by frezbo** [comment]
does this need any userspace daemon or something to be running, or just the CSI is enough?

**Comment by frezbo** [comment]
Okay, this enabled some extra config too:

Running `make old-defconfig`

```bash
diff --git a/kernel/build/config-amd64 b/kernel/build/config-amd64
index 40d8210..08000e6 100644
--- a/kernel/build/config-amd64
+++ b/kernel/build/config-amd64
@@ -1971,6 +1971,7 @@ CONFIG_BLK_DEV_RBD=y
 #
 # NVME Support
 #
+CONFIG_NVME_COMMON=y
 CONFIG_NVME_CORE=y
 CONFIG_BLK_DEV_NVME=y
 CONFIG_NVME_MULTIPATH=y
@@ -5274,6 +5275,7 @@ CONFIG_CRYPTO_RNG_DEFAULT=y
 CONFIG_CRYPTO_AKCIPHER2=y
 CONFIG_CRYPTO_AKCIPHER=y
 CONFIG_CRYPTO_KPP2=y
+CONFIG_CRYPTO_KPP=y
 CONFIG_CRYPTO_ACOMP2=y
 CONFIG_CRYPTO_MANAGER=y
 CONFIG_CRYPTO_MANAGER2=y
@@ -5294,7 +5296,8 @@ CONFIG_CRYPTO_ENGINE=y
 # Public-key cryptography
 #
 CONFIG_CRYPTO_RSA=y
-# CONFIG_CRYPTO_DH is not set
+CONFIG_CRYPTO_DH=y
+CONFIG_CRYPTO_DH_RFC7919_GROUPS=y
 # CONFIG_CRYPTO_ECDH is not set
 # CONFIG_CRYPTO_ECDSA is not set
 # CONFIG_CRYPTO_ECRDSA is not set

```

**Review by frezbo — APPROVED** [review]
I'm not sure if these needs to be modules or statically compiled in :shrug:

**Comment by ishioni** [comment]
Multipath needs to be compiled in I think. The auth can be a module if possible. Both were compiled as Y in Ubuntu, hence why I chose that

**Pull request merged**
