### PR TITLE
refactor: move device drivers out as kernel modules

### PR DESCRIPTION
**Pull request by smira**
`udevd` is going to auto-load them, so there's no change from the user perspective

Benefits:

* boot time (smaller kernel)
* smaller attack surface potentially (less code loaded always)

This got only applied for amd64 for now, as arm64 had issues with auto-loading modules (need to investigate more, but easy to apply same patch).

### CODE REVIEW

**Comment by smira** [comment]
raw diff of new modules to be included into `initramfs`:

```diff
28a29,31
> ./lib/modules/6.1.41-talos/kernel/drivers/net/ethernet/aquantia
> ./lib/modules/6.1.41-talos/kernel/drivers/net/ethernet/aquantia/atlantic
> ./lib/modules/6.1.41-talos/kernel/drivers/net/ethernet/aquantia/atlantic/atlantic.ko
31a35,72
> ./lib/modules/6.1.41-talos/kernel/drivers/net/ethernet/broadcom
> ./lib/modules/6.1.41-talos/kernel/drivers/net/ethernet/broadcom/bnx2.ko
> ./lib/modules/6.1.41-talos/kernel/drivers/net/ethernet/broadcom/bnx2x
> ./lib/modules/6.1.41-talos/kernel/drivers/net/ethernet/broadcom/bnx2x/bnx2x.ko
> ./lib/modules/6.1.41-talos/kernel/drivers/net/ethernet/broadcom/bnxt
> ./lib/modules/6.1.41-talos/kernel/drivers/net/ethernet/broadcom/bnxt/bnxt_en.ko
> ./lib/modules/6.1.41-talos/kernel/drivers/net/ethernet/cisco
> ./lib/modules/6.1.41-talos/kernel/drivers/net/ethernet/cisco/enic
> ./lib/modules/6.1.41-talos/kernel/drivers/net/ethernet/cisco/enic/enic.ko
> ./lib/modules/6.1.41-talos/kernel/drivers/net/ethernet/emulex
> ./lib/modules/6.1.41-talos/kernel/drivers/net/ethernet/emulex/benet
> ./lib/modules/6.1.41-talos/kernel/drivers/net/ethernet/emulex/benet/be2net.ko
> ./lib/modules/6.1.41-talos/kernel/drivers/net/ethernet/intel
> ./lib/modules/6.1.41-talos/kernel/drivers/net/ethernet/intel/e1000
> ./lib/modules/6.1.41-talos/kernel/drivers/net/ethernet/intel/e1000/e1000.ko
> ./lib/modules/6.1.41-talos/kernel/drivers/net/ethernet/intel/e1000e
> ./lib/modules/6.1.41-talos/kernel/drivers/net/ethernet/intel/e1000e/e1000e.ko
> ./lib/modules/6.1.41-talos/kernel/drivers/net/ethernet/intel/e100.ko
> ./lib/modules/6.1.41-talos/kernel/drivers/net/ethernet/intel/i40e
> ./lib/modules/6.1.41-talos/kernel/drivers/net/ethernet/intel/i40e/i40e.ko
> ./lib/modules/6.1.41-talos/kernel/drivers/net/ethernet/intel/iavf
> ./lib/modules/6.1.41-talos/kernel/drivers/net/ethernet/intel/iavf/iavf.ko
> ./lib/modules/6.1.41-talos/kernel/drivers/net/ethernet/intel/ice
> ./lib/modules/6.1.41-talos/kernel/drivers/net/ethernet/intel/ice/ice.ko
> ./lib/modules/6.1.41-talos/kernel/drivers/net/ethernet/intel/igb
> ./lib/modules/6.1.41-talos/kernel/drivers/net/ethernet/intel/igb/igb.ko
> ./lib/modules/6.1.41-talos/kernel/drivers/net/ethernet/intel/igbvf
> ./lib/modules/6.1.41-talos/kernel/drivers/net/ethernet/intel/igbvf/igbvf.ko
> ./lib/modules/6.1.41-talos/kernel/drivers/net/ethernet/intel/igc
> ./lib/modules/6.1.41-talos/kernel/drivers/net/ethernet/intel/igc/igc.ko
> ./lib/modules/6.1.41-talos/kernel/drivers/net/ethernet/intel/ixgb
> ./lib/modules/6.1.41-talos/kernel/drivers/net/ethernet/intel/ixgb/ixgb.ko
> ./lib/modules/6.1.41-talos/kernel/drivers/net/ethernet/intel/ixgbe
> ./lib/modules/6.1.41-talos/kernel/drivers/net/ethernet/intel/ixgbe/ixgbe.ko
> ./lib/modules/6.1.41-talos/kernel/drivers/net/ethernet/intel/ixgbevf
> ./lib/modules/6.1.41-talos/kernel/drivers/net/ethernet/intel/ixgbevf/ixgbevf.ko
> ./lib/modules/6.1.41-talos/kernel/drivers/net/ethernet/marvell
> ./lib/modules/6.1.41-talos/kernel/drivers/net/ethernet/marvell/sky2.ko
46a88,98
> ./lib/modules/6.1.41-talos/kernel/drivers/net/ethernet/qlogic
> ./lib/modules/6.1.41-talos/kernel/drivers/net/ethernet/qlogic/qed
> ./lib/modules/6.1.41-talos/kernel/drivers/net/ethernet/qlogic/qed/qed.ko
> ./lib/modules/6.1.41-talos/kernel/drivers/net/ethernet/qlogic/qede
> ./lib/modules/6.1.41-talos/kernel/drivers/net/ethernet/qlogic/qede/qede.ko
> ./lib/modules/6.1.41-talos/kernel/drivers/net/ethernet/qlogic/qlcnic
> ./lib/modules/6.1.41-talos/kernel/drivers/net/ethernet/qlogic/qlcnic/qlcnic.ko
> ./lib/modules/6.1.41-talos/kernel/drivers/net/ethernet/realtek
> ./lib/modules/6.1.41-talos/kernel/drivers/net/ethernet/realtek/8139too.ko
> ./lib/modules/6.1.41-talos/kernel/drivers/net/ethernet/realtek/r8169.ko
> ./lib/modules/6.1.41-talos/kernel/drivers/net/mdio.ko
80a133,145
> ./lib/modules/6.1.41-talos/kernel/drivers/net/vmxnet3
> ./lib/modules/6.1.41-talos/kernel/drivers/net/vmxnet3/vmxnet3.ko
> ./lib/modules/6.1.41-talos/kernel/drivers/scsi
> ./lib/modules/6.1.41-talos/kernel/drivers/scsi/aacraid
> ./lib/modules/6.1.41-talos/kernel/drivers/scsi/aacraid/aacraid.ko
> ./lib/modules/6.1.41-talos/kernel/drivers/scsi/hpsa.ko
> ./lib/modules/6.1.41-talos/kernel/drivers/scsi/megaraid
> ./lib/modules/6.1.41-talos/kernel/drivers/scsi/megaraid/megaraid_sas.ko
> ./lib/modules/6.1.41-talos/kernel/drivers/scsi/mpt3sas
> ./lib/modules/6.1.41-talos/kernel/drivers/scsi/mpt3sas/mpt3sas.ko
> ./lib/modules/6.1.41-talos/kernel/drivers/scsi/smartpqi
> ./lib/modules/6.1.41-talos/kernel/drivers/scsi/smartpqi/smartpqi.ko
> ./lib/modules/6.1.41-talos/kernel/drivers/scsi/vmw_pvscsi.ko
120c185
< 37 directories, 81 files
---
> 70 directories, 113 files
```

full tree as built, previously:

<details>

```
[4.0K]  .
├── [4.0K]  boot
│   └── [ 18M]  vmlinuz
├── [4.0K]  certs
│   └── [1.4K]  signing_key.x509
├── [4.0K]  dtb
└── [4.0K]  lib
    └── [4.0K]  modules
        └── [4.0K]  6.1.41-talos
            ├── [4.0K]  kernel
            │   ├── [4.0K]  crypto
            │   │   ├── [4.0K]  async_tx
            │   │   │   ├── [9.9K]  async_memcpy.ko
            │   │   │   ├── [ 19K]  async_pq.ko
            │   │   │   ├── [9.5K]  async_raid6_recov.ko
            │   │   │   ├── [ 13K]  async_tx.ko
            │   │   │   └── [ 16K]  async_xor.ko
            │   │   └── [ 28K]  xor.ko
            │   ├── [4.0K]  drivers
            │   │   ├── [4.0K]  infiniband
            │   │   │   └── [4.0K]  sw
            │   │   │       └── [4.0K]  rxe
            │   │   │           └── [233K]  rdma_rxe.ko
            │   │   ├── [4.0K]  md
            │   │   │   ├── [ 79K]  dm-raid.ko
            │   │   │   └── [320K]  raid456.ko
            │   │   ├── [4.0K]  net
            │   │   │   ├── [4.0K]  ethernet
            │   │   │   │   ├── [4.0K]  atheros
            │   │   │   │   │   └── [4.0K]  alx
            │   │   │   │   │       └── [103K]  alx.ko
            │   │   │   │   └── [4.0K]  mellanox
            │   │   │   │       ├── [4.0K]  mlx4
            │   │   │   │       │   ├── [824K]  mlx4_core.ko
            │   │   │   │       │   └── [332K]  mlx4_en.ko
            │   │   │   │       ├── [4.0K]  mlx5
            │   │   │   │       │   └── [4.0K]  core
            │   │   │   │       │       └── [3.5M]  mlx5_core.ko
            │   │   │   │       ├── [4.0K]  mlxfw
            │   │   │   │       │   └── [ 47K]  mlxfw.ko
            │   │   │   │       └── [4.0K]  mlxsw
            │   │   │   │           ├── [460K]  mlxsw_core.ko
            │   │   │   │           ├── [ 27K]  mlxsw_i2c.ko
            │   │   │   │           ├── [ 40K]  mlxsw_minimal.ko
            │   │   │   │           ├── [ 77K]  mlxsw_pci.ko
            │   │   │   │           └── [1.5M]  mlxsw_spectrum.ko
            │   │   │   ├── [4.0K]  phy
            │   │   │   │   ├── [ 12K]  ax88796b.ko
            │   │   │   │   └── [ 21K]  smsc.ko
            │   │   │   ├── [ 51K]  thunderbolt-net.ko
            │   │   │   └── [4.0K]  usb
            │   │   │       ├── [ 54K]  aqc111.ko
            │   │   │       ├── [102K]  asix.ko
            │   │   │       ├── [ 59K]  ax88179_178a.ko
            │   │   │       ├── [ 16K]  cdc_eem.ko
            │   │   │       ├── [ 33K]  cdc_ether.ko
            │   │   │       ├── [ 30K]  cdc_mbim.ko
            │   │   │       ├── [ 67K]  cdc_ncm.ko
            │   │   │       ├── [ 23K]  cdc-phonet.ko
            │   │   │       ├── [ 15K]  cdc_subset.ko
            │   │   │       ├── [ 21K]  cx82310_eth.ko
            │   │   │       ├── [ 32K]  dm9601.ko
            │   │   │       ├── [ 14K]  gl620a.ko
            │   │   │       ├── [ 19K]  huawei_cdc_ncm.ko
            │   │   │       ├── [ 17K]  int51x1.ko
            │   │   │       ├── [ 17K]  kalmia.ko
            │   │   │       ├── [ 18K]  lg-vl600.ko
            │   │   │       ├── [ 29K]  mcs7830.ko
            │   │   │       ├── [ 17K]  net1080.ko
            │   │   │       ├── [ 11K]  plusb.ko
            │   │   │       ├── [103K]  qmi_wwan.ko
            │   │   │       ├── [ 14K]  r8153_ecm.ko
            │   │   │       ├── [ 31K]  rndis_host.ko
            │   │   │       ├── [ 35K]  sierra_net.ko
            │   │   │       ├── [ 79K]  smsc75xx.ko
            │   │   │       ├── [ 72K]  smsc95xx.ko
            │   │   │       ├── [ 29K]  sr9700.ko
            │   │   │       ├── [ 37K]  sr9800.ko
            │   │   │       ├── [ 88K]  usbnet.ko
            │   │   │       └── [ 16K]  zaurus.ko
            │   │   ├── [4.0K]  thunderbolt
            │   │   │   └── [690K]  thunderbolt.ko
            │   │   ├── [4.0K]  usb
            │   │   │   ├── [4.0K]  class
            │   │   │   │   └── [ 47K]  cdc-wdm.ko
            │   │   │   └── [4.0K]  serial
            │   │   │       ├── [181K]  option.ko
            │   │   │       └── [ 29K]  usb_wwan.ko
            │   │   └── [4.0K]  virtio
            │   │       ├── [ 46K]  virtio_balloon.ko
            │   │       ├── [ 27K]  virtio_input.ko
            │   │       ├── [ 33K]  virtio_mmio.ko
            │   │       ├── [ 60K]  virtio_pci.ko
            │   │       ├── [ 16K]  virtio_pci_legacy_dev.ko
            │   │       └── [ 31K]  virtio_pci_modern_dev.ko
            │   ├── [4.0K]  lib
            │   │   ├── [ 98K]  objagg.ko
            │   │   ├── [ 14K]  parman.ko
            │   │   └── [4.0K]  raid6
            │   │       └── [144K]  raid6_pq.ko
            │   └── [4.0K]  net
            │       ├── [4.0K]  ipv4
            │       │   └── [ 57K]  ip_gre.ko
            │       └── [4.0K]  openvswitch
            │           └── [9.3K]  vport-gre.ko
            ├── [117K]  modules.alias
            ├── [114K]  modules.alias.bin
            ├── [ 27K]  modules.builtin
            ├── [ 28K]  modules.builtin.alias.bin
            ├── [ 31K]  modules.builtin.bin
            ├── [253K]  modules.builtin.modinfo
            ├── [5.5K]  modules.dep
            ├── [8.1K]  modules.dep.bin
            ├── [   0]  modules.devname
            ├── [2.5K]  modules.order
            ├── [  55]  modules.softdep
            ├── [ 32K]  modules.symbols
            └── [ 37K]  modules.symbols.bin

37 directories, 81 files
```

</details>

new tree, with modules out:

<details>

```
[4.0K]  .
├── [4.0K]  boot
│   └── [ 16M]  vmlinuz
├── [4.0K]  certs
│   └── [1.4K]  signing_key.x509
├── [4.0K]  dtb
└── [4.0K]  lib
    └── [4.0K]  modules
        └── [4.0K]  6.1.41-talos
            ├── [4.0K]  kernel
            │   ├── [4.0K]  crypto
            │   │   ├── [4.0K]  async_tx
            │   │   │   ├── [9.9K]  async_memcpy.ko
            │   │   │   ├── [ 19K]  async_pq.ko
            │   │   │   ├── [9.5K]  async_raid6_recov.ko
            │   │   │   ├── [ 13K]  async_tx.ko
            │   │   │   └── [ 16K]  async_xor.ko
            │   │   └── [ 28K]  xor.ko
            │   ├── [4.0K]  drivers
            │   │   ├── [4.0K]  infiniband
            │   │   │   └── [4.0K]  sw
            │   │   │       └── [4.0K]  rxe
            │   │   │           └── [233K]  rdma_rxe.ko
            │   │   ├── [4.0K]  md
            │   │   │   ├── [ 79K]  dm-raid.ko
            │   │   │   └── [321K]  raid456.ko
            │   │   ├── [4.0K]  net
            │   │   │   ├── [4.0K]  ethernet
            │   │   │   │   ├── [4.0K]  aquantia
            │   │   │   │   │   └── [4.0K]  atlantic
            │   │   │   │   │       └── [517K]  atlantic.ko
            │   │   │   │   ├── [4.0K]  atheros
            │   │   │   │   │   └── [4.0K]  alx
            │   │   │   │   │       └── [104K]  alx.ko
            │   │   │   │   ├── [4.0K]  broadcom
            │   │   │   │   │   ├── [188K]  bnx2.ko
            │   │   │   │   │   ├── [4.0K]  bnx2x
            │   │   │   │   │   │   └── [1.6M]  bnx2x.ko
            │   │   │   │   │   └── [4.0K]  bnxt
            │   │   │   │   │       └── [721K]  bnxt_en.ko
            │   │   │   │   ├── [4.0K]  cisco
            │   │   │   │   │   └── [4.0K]  enic
            │   │   │   │   │       └── [241K]  enic.ko
            │   │   │   │   ├── [4.0K]  emulex
            │   │   │   │   │   └── [4.0K]  benet
            │   │   │   │   │       └── [355K]  be2net.ko
            │   │   │   │   ├── [4.0K]  intel
            │   │   │   │   │   ├── [4.0K]  e1000
            │   │   │   │   │   │   └── [259K]  e1000.ko
            │   │   │   │   │   ├── [4.0K]  e1000e
            │   │   │   │   │   │   └── [527K]  e1000e.ko
            │   │   │   │   │   ├── [106K]  e100.ko
            │   │   │   │   │   ├── [4.0K]  i40e
            │   │   │   │   │   │   └── [960K]  i40e.ko
            │   │   │   │   │   ├── [4.0K]  iavf
            │   │   │   │   │   │   └── [358K]  iavf.ko
            │   │   │   │   │   ├── [4.0K]  ice
            │   │   │   │   │   │   └── [1.6M]  ice.ko
            │   │   │   │   │   ├── [4.0K]  igb
            │   │   │   │   │   │   └── [498K]  igb.ko
            │   │   │   │   │   ├── [4.0K]  igbvf
            │   │   │   │   │   │   └── [108K]  igbvf.ko
            │   │   │   │   │   ├── [4.0K]  igc
            │   │   │   │   │   │   └── [289K]  igc.ko
            │   │   │   │   │   ├── [4.0K]  ixgb
            │   │   │   │   │   │   └── [111K]  ixgb.ko
            │   │   │   │   │   ├── [4.0K]  ixgbe
            │   │   │   │   │   │   └── [733K]  ixgbe.ko
            │   │   │   │   │   └── [4.0K]  ixgbevf
            │   │   │   │   │       └── [178K]  ixgbevf.ko
            │   │   │   │   ├── [4.0K]  marvell
            │   │   │   │   │   └── [159K]  sky2.ko
            │   │   │   │   ├── [4.0K]  mellanox
            │   │   │   │   │   ├── [4.0K]  mlx4
            │   │   │   │   │   │   ├── [825K]  mlx4_core.ko
            │   │   │   │   │   │   └── [333K]  mlx4_en.ko
            │   │   │   │   │   ├── [4.0K]  mlx5
            │   │   │   │   │   │   └── [4.0K]  core
            │   │   │   │   │   │       └── [3.5M]  mlx5_core.ko
            │   │   │   │   │   ├── [4.0K]  mlxfw
            │   │   │   │   │   │   └── [ 47K]  mlxfw.ko
            │   │   │   │   │   └── [4.0K]  mlxsw
            │   │   │   │   │       ├── [461K]  mlxsw_core.ko
            │   │   │   │   │       ├── [ 27K]  mlxsw_i2c.ko
            │   │   │   │   │       ├── [ 41K]  mlxsw_minimal.ko
            │   │   │   │   │       ├── [ 77K]  mlxsw_pci.ko
            │   │   │   │   │       └── [1.5M]  mlxsw_spectrum.ko
            │   │   │   │   ├── [4.0K]  qlogic
            │   │   │   │   │   ├── [4.0K]  qed
            │   │   │   │   │   │   └── [1.3M]  qed.ko
            │   │   │   │   │   ├── [4.0K]  qede
            │   │   │   │   │   │   └── [358K]  qede.ko
            │   │   │   │   │   └── [4.0K]  qlcnic
            │   │   │   │   │       └── [806K]  qlcnic.ko
            │   │   │   │   └── [4.0K]  realtek
            │   │   │   │       ├── [ 71K]  8139too.ko
            │   │   │   │       └── [204K]  r8169.ko
            │   │   │   ├── [ 19K]  mdio.ko
            │   │   │   ├── [4.0K]  phy
            │   │   │   │   ├── [ 12K]  ax88796b.ko
            │   │   │   │   └── [ 21K]  smsc.ko
            │   │   │   ├── [ 51K]  thunderbolt-net.ko
            │   │   │   ├── [4.0K]  usb
            │   │   │   │   ├── [ 54K]  aqc111.ko
            │   │   │   │   ├── [102K]  asix.ko
            │   │   │   │   ├── [ 59K]  ax88179_178a.ko
            │   │   │   │   ├── [ 16K]  cdc_eem.ko
            │   │   │   │   ├── [ 33K]  cdc_ether.ko
            │   │   │   │   ├── [ 30K]  cdc_mbim.ko
            │   │   │   │   ├── [ 67K]  cdc_ncm.ko
            │   │   │   │   ├── [ 23K]  cdc-phonet.ko
            │   │   │   │   ├── [ 15K]  cdc_subset.ko
            │   │   │   │   ├── [ 21K]  cx82310_eth.ko
            │   │   │   │   ├── [ 32K]  dm9601.ko
            │   │   │   │   ├── [ 14K]  gl620a.ko
            │   │   │   │   ├── [ 19K]  huawei_cdc_ncm.ko
            │   │   │   │   ├── [ 17K]  int51x1.ko
            │   │   │   │   ├── [ 17K]  kalmia.ko
            │   │   │   │   ├── [ 18K]  lg-vl600.ko
            │   │   │   │   ├── [ 29K]  mcs7830.ko
            │   │   │   │   ├── [ 17K]  net1080.ko
            │   │   │   │   ├── [ 11K]  plusb.ko
            │   │   │   │   ├── [103K]  qmi_wwan.ko
            │   │   │   │   ├── [ 14K]  r8153_ecm.ko
            │   │   │   │   ├── [ 31K]  rndis_host.ko
            │   │   │   │   ├── [ 35K]  sierra_net.ko
            │   │   │   │   ├── [ 79K]  smsc75xx.ko
            │   │   │   │   ├── [ 72K]  smsc95xx.ko
            │   │   │   │   ├── [ 29K]  sr9700.ko
            │   │   │   │   ├── [ 38K]  sr9800.ko
            │   │   │   │   ├── [ 88K]  usbnet.ko
            │   │   │   │   └── [ 16K]  zaurus.ko
            │   │   │   └── [4.0K]  vmxnet3
            │   │   │       └── [128K]  vmxnet3.ko
            │   │   ├── [4.0K]  scsi
            │   │   │   ├── [4.0K]  aacraid
            │   │   │   │   └── [319K]  aacraid.ko
            │   │   │   ├── [231K]  hpsa.ko
            │   │   │   ├── [4.0K]  megaraid
            │   │   │   │   └── [379K]  megaraid_sas.ko
            │   │   │   ├── [4.0K]  mpt3sas
            │   │   │   │   └── [790K]  mpt3sas.ko
            │   │   │   ├── [4.0K]  smartpqi
            │   │   │   │   └── [263K]  smartpqi.ko
            │   │   │   └── [ 52K]  vmw_pvscsi.ko
            │   │   ├── [4.0K]  thunderbolt
            │   │   │   └── [690K]  thunderbolt.ko
            │   │   ├── [4.0K]  usb
            │   │   │   ├── [4.0K]  class
            │   │   │   │   └── [ 47K]  cdc-wdm.ko
            │   │   │   └── [4.0K]  serial
            │   │   │       ├── [181K]  option.ko
            │   │   │       └── [ 29K]  usb_wwan.ko
            │   │   └── [4.0K]  virtio
            │   │       ├── [ 46K]  virtio_balloon.ko
            │   │       ├── [ 27K]  virtio_input.ko
            │   │       ├── [ 33K]  virtio_mmio.ko
            │   │       ├── [ 60K]  virtio_pci.ko
            │   │       ├── [ 16K]  virtio_pci_legacy_dev.ko
            │   │       └── [ 31K]  virtio_pci_modern_dev.ko
            │   ├── [4.0K]  lib
            │   │   ├── [ 98K]  objagg.ko
            │   │   ├── [ 14K]  parman.ko
            │   │   └── [4.0K]  raid6
            │   │       └── [144K]  raid6_pq.ko
            │   └── [4.0K]  net
            │       ├── [4.0K]  ipv4
            │       │   └── [ 57K]  ip_gre.ko
            │       └── [4.0K]  openvswitch
            │           └── [9.3K]  vport-gre.ko
            ├── [169K]  modules.alias
            ├── [153K]  modules.alias.bin
            ├── [ 26K]  modules.builtin
            ├── [ 28K]  modules.builtin.alias.bin
            ├── [ 30K]  modules.builtin.bin
            ├── [228K]  modules.builtin.modinfo
            ├── [7.1K]  modules.dep
            ├── [ 11K]  modules.dep.bin
            ├── [   0]  modules.devname
            ├── [3.9K]  modules.order
            ├── [  82]  modules.softdep
            ├── [ 33K]  modules.symbols
            └── [ 39K]  modules.symbols.bin

70 directories, 113 files
```

</details>

Raw size (note that kernel is compressed, but modules are not):

* old: raw 30M, 20839964 bytes xz'd 
* new: raw 42M, 21243536 bytes xz'd

**Review by Unix4ever — APPROVED** [review]

**Comment by smira** [comment]
just the kernel itself:

* old 19M
* new 16M

for comparison, Ubuntu kernel is 14M

**Review by frezbo — APPROVED** [review]
:cool:

**Pull request merged**
