### PR TITLE
backports: for Talos v1.4.1

### PR DESCRIPTION
**Pull request by smira**
PRs backported:

- #710 
- #714

### CODE REVIEW

**Comment by Unix4ever** [comment]
should we wait until https://github.com/siderolabs/talos/pull/7147 is merged?

**Comment by smira** [comment]
> should we wait until [siderolabs/talos#7147](https://github.com/siderolabs/talos/pull/7147) is merged?

this is `pkgs`, not `talos` :)

**Comment by Unix4ever** [comment]
oh, sorry, I'm blind :D

**Pull request merged**
