### PR TITLE
feat: update Linux to 6.6.59

### PR DESCRIPTION
**Pull request by smira**
Latest LTS kernel.

### CODE REVIEW

**Review by frezbo — APPROVED** [review]

**Comment by frezbo** [comment]
> `drbd` build is broken

hmm seems some function signature changes, probably they have to publish a new patch

**Comment by frezbo** [comment]
Seems a patch got merged an hour ago:https://github.com/LINBIT/drbd/commit/ebe82c19178ffc5a9f59bb4539d98503688398b8

**Comment by smira** [comment]
The commit which breaks things: b94e5375ec66f4fe40ed7591b7fc8a4505c922d4:

```diff
commit b94e5375ec66f4fe40ed7591b7fc8a4505c922d4
Author: Eric Dumazet <edumazet@google.com>
Date:   Fri Oct 11 17:12:17 2024 +0000

    genetlink: hold RCU in genlmsg_mcast()
    
    [ Upstream commit 56440d7ec28d60f8da3bfa09062b3368ff9b16db ]
    
    While running net selftests with CONFIG_PROVE_RCU_LIST=y I saw
    one lockdep splat [1].
    
    genlmsg_mcast() uses for_each_net_rcu(), and must therefore hold RCU.
    
    Instead of letting all callers guard genlmsg_multicast_allns()
    with a rcu_read_lock()/rcu_read_unlock() pair, do it in genlmsg_mcast().
    
    This also means the @flags parameter is useless, we need to always use
    GFP_ATOMIC.
```

**Pull request merged**
