### PR TITLE
feat: build dvb kernel modules and CX23885

### PR DESCRIPTION
**Pull request by samip5**
Fixes https://github.com/siderolabs/pkgs/issues/990
This also needs dvb firmware for said tuner, but this is needed first and these need to be packaged to an extension.

### CODE REVIEW

**Comment by frezbo** [comment]
@samip5 are these also required for arm64? Also do you have a corresponding extensions PR? Otherwise this'll go into 1.10

**Comment by samip5** [comment]
I'm not sure if the drivers will work on arm64, but I at least don't need them in arm64, so that's why I have added it only to amd64. I have a corresponding extensions pr for the firmware part, but not for the actual dvb modules yet.

So are you referring to the extension of including the kernel modules this builds as a extension?

**Comment by frezbo** [comment]
> So are you referring to the extension of including the kernel modules this builds as a extension?

yes, these won;t be shipped with core talos

**Comment by frezbo** [comment]
Re-created as #1102, since cannot push PR created from org

**Pull request closed without merging**
