### PR TITLE
kernel: enable most common amd64 watchdog drivers

### PR DESCRIPTION
**Pull request by dsseng**
Related to https://github.com/siderolabs/talos/pull/8313

### CODE REVIEW

**Review by smira — APPROVED** [review]

**Comment by smira** [comment]
```diff
31a32,34
> ./lib/modules/6.6.20-talos/kernel/drivers/char
> ./lib/modules/6.6.20-talos/kernel/drivers/char/ipmi
> ./lib/modules/6.6.20-talos/kernel/drivers/char/ipmi/ipmi_watchdog.ko
122a126,128
> ./lib/modules/6.6.20-talos/kernel/drivers/mfd
> ./lib/modules/6.6.20-talos/kernel/drivers/mfd/lpc_ich.ko
> ./lib/modules/6.6.20-talos/kernel/drivers/mfd/mfd-core.ko
314a321,328
> ./lib/modules/6.6.20-talos/kernel/drivers/watchdog
> ./lib/modules/6.6.20-talos/kernel/drivers/watchdog/i6300esb.ko
> ./lib/modules/6.6.20-talos/kernel/drivers/watchdog/iTCO_vendor_support.ko
> ./lib/modules/6.6.20-talos/kernel/drivers/watchdog/iTCO_wdt.ko
> ./lib/modules/6.6.20-talos/kernel/drivers/watchdog/sp5100_tco.ko
> ./lib/modules/6.6.20-talos/kernel/drivers/watchdog/watchdog.ko
> ./lib/modules/6.6.20-talos/kernel/drivers/watchdog/wdat_wdt.ko
> ./lib/modules/6.6.20-talos/kernel/drivers/watchdog/xen_wdt.ko
345c359
< 125 directories, 218 files
---
> 129 directories, 228 files
```

**Comment by frezbo** [comment]
do we need all of these?

**Pull request merged**
