### PR TITLE
feat: bring Linux to 6.1.76

### PR DESCRIPTION
**Pull request by smira**
Latest LTS for Talos 1.6.x.

### CODE REVIEW

**Review by utkuozdemir — APPROVED** [review]

**Review by frezbo — APPROVED** [review]

**Comment by smira** [comment]
Blocked on https://github.com/NVIDIA/open-gpu-kernel-modules/issues/594

**Comment by smira** [comment]
a patch to workaround the build issue: https://github.com/gentoo/gentoo/blob/c64caf53/x11-drivers/nvidia-drivers/files/nvidia-drivers-470.223.02-gpl-pfn_valid.patch

**Comment by smira** [comment]
> a patch to workaround the build issue: https://github.com/gentoo/gentoo/blob/c64caf53/x11-drivers/nvidia-drivers/files/nvidia-drivers-470.223.02-gpl-pfn_valid.patch

no longer needed, as the upstream Linux reverted the GPLification of the symbol.

**Pull request merged**
