### PR TITLE
feat: enable VFIO also on amd64

### PR DESCRIPTION
**Pull request by yoctozepto**
On arm64 platform, the relevant VFIO configs are enabled already. This patch synchronizes both.

### CODE REVIEW

**Comment by yoctozepto** [comment]
I had a thought - would it more preferable modularised instead of builtin?

Not that VFIO does anything by default in either case (it must be let to control a device, otherwise it just sits there).

**Comment by smira** [comment]
```diff
263a264,270
> ./lib/modules/6.1.67-talos/kernel/drivers/vfio
> ./lib/modules/6.1.67-talos/kernel/drivers/vfio/pci
> ./lib/modules/6.1.67-talos/kernel/drivers/vfio/pci/vfio-pci-core.ko
> ./lib/modules/6.1.67-talos/kernel/drivers/vfio/pci/vfio-pci.ko
> ./lib/modules/6.1.67-talos/kernel/drivers/vfio/vfio_iommu_type1.ko
> ./lib/modules/6.1.67-talos/kernel/drivers/vfio/vfio.ko
> ./lib/modules/6.1.67-talos/kernel/drivers/vfio/vfio_virqfd.ko
301c308
< 109 directories, 190 files
---
> 111 directories, 195 files
```

Size:

```
            │   │   ├── [4.0K]  vfio
            │   │   │   ├── [4.0K]  pci
            │   │   │   │   ├── [155K]  vfio-pci-core.ko
            │   │   │   │   └── [ 23K]  vfio-pci.ko
            │   │   │   ├── [ 83K]  vfio_iommu_type1.ko
            │   │   │   ├── [ 90K]  vfio.ko
            │   │   │   └── [ 15K]  vfio_virqfd.ko
```

**Comment by yoctozepto** [comment]
I approve from my side. This is in vein with the Talos approach as I see it. Thanks.

**Review by smira — APPROVED** [review]
reworked to use modules on both architectures

**Pull request merged**
