### PR TITLE
fix: patch ipmitool IANA URL

### PR DESCRIPTION
**Pull request by smira**
See https://github.com/siderolabs/sidero/issues/1013 
See https://github.com/ipmitool/ipmitool/issues/377

Signed-off-by: Andrey Smirnov <andrey.smirnov@talos-systems.com>

### CODE REVIEW

**Review by frezbo — APPROVED** [review]
Nice, I though it was the build process that was broken :sweat_smile:

**Comment by smira** [comment]
> Nice, I though it was the build process that was broken sweat_smile

:shrug: the released version is broken, but there's no new release :facepalm:

**Comment by frezbo** [comment]
> > Nice, I though it was the build process that was broken sweat_smile
> 
> shrug the released version is broken, but there's no new release facepalm

should we add a `test` section in `pkg.yaml` that just run `ipmitool` to make sure it works? :thinking:

**Comment by smira** [comment]
I think a test requires at least some valid IPMI target. But in general I agree - we should test more in `pkgs` if possible

**Review by Unix4ever — APPROVED** [review]

**Pull request merged**
