### PR TITLE
feat: add Pine64 SOQuartz SBC on CM4 I/O board

### PR DESCRIPTION
**Pull request by pl4nty**
Updates U-Boot to v2024.01 and adds support for the [Pine64 SOQuartz](https://wiki.pine64.org/wiki/SOQuartz) SBC when mounted on a CM4 I/O board.

Happy to split this into two PRs, particularly because the [lack of v2024 patches for the Jetson Nano](https://github.com/OE4T/u-boot-tegra) likely breaks support for it. May need to retain v2023 like @nberlee suggested on Slack. Nico probably has a better perspective of the RPi/RockPi4 patch changes too - I haven't tested those patches, only rebased as-is.

New kernel configs are from the [SOQuartz Development wiki](https://wiki.pine64.org/wiki/Quartz64_Development#Linux_Kernel_Config_Options), but I skipped these SND/VIDEO configs:

<table>
<tr>
 <td>CONFIG_SND_SOC_ROCKCHIP_I2S_TDM
 <td>for Analog and HDMI audio
<tr>
 <td>CONFIG_SND_SOC_RK817
 <td>for Analog audio on the Model A
<tr>
 <td>CONFIG_SND_SOC_ROCKCHIP_SPDIF 
 <td>SPDIF audio
<tr>
 <td>CONFIG_VIDEO_HANTRO_ROCKCHIP 
 <td>Hardware video decoder support
</table>

Tested in a Turing Pi 2 I/O board with various U-Boot release candidates. I've only used an SD card, but I'll have an eMMC module to test soon.

Marked as draft pending these deps:
- [ ] U-Boot v2024.01 scheduled for 8 Jan 2024
- [ ] [rk3568 Arm Trusted Firmware](https://review.trustedfirmware.org/c/TF-A/trusted-firmware-a/+/16952) pending maintainer review

### CODE REVIEW

**Comment by frezbo** [comment]
Will look into this once https://github.com/siderolabs/talos/issues/8065 is addressed

**Comment by pl4nty** [comment]
@frezbo sounds good, should I submit a draft to https://github.com/siderolabs/talos as well?

I've just finished testing - eMMC works, but `CONFIG_SENSORS_NCT6683` from #846 causes a kernel panic

**Comment by frezbo** [comment]
> @frezbo sounds good, should I submit a draft to https://github.com/siderolabs/talos as well?
> 
> I've just finished testing - eMMC works, but `CONFIG_SENSORS_NCT6683` from #846 causes a kernel panic

yes, please, so that the work doesn't get lot, will revisit once we split up

**Comment by frezbo** [comment]
@pl4nty could you move this to https://github.com/siderolabs/sbc-rockchip/

**Comment by pl4nty** [comment]
Closing in favour of siderolabs/sbc-rockchip#7

**Pull request closed without merging**
