### PR TITLE
feat: enable sriov

### PR DESCRIPTION
**Pull request by sergelogvinov**
* support HyperV sr-iov network
* suppprt SRIOV CNI plugin for amd64, arm64 already has it.

https://github.com/siderolabs/talos/issues/7415

### CODE REVIEW

**Review by frezbo — COMMENTED** [review]
would building these as modules work?

**Comment by smira** [comment]
> would building these as modules work?

I think base PCI_HYPERV can't be loaded dynamically by udev, and parts of bnx2 we already have built-in, so enabling one more piece doesn't sound like it should be a module?

**Review by smira — APPROVED** [review]

**Pull request merged**
